# This is a basic workflow that is manually triggered
# Objetivo: Ao lançar uma PR para branch de develop, será realizado um trigger que irá esperar 
# que um reviewer em especifico de ok para que automaticamente essa PR seja recriada e lançada para outra branch.

name: Automate pulll request workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Test'
        default: 'Write something...'
        required: true

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "feature, automated pr"
          pr_title: "[Example] Simple demo"
