# This is a basic workflow that is manually triggered
# Objetivo: Ao lançar uma PR para branch de develop, será realizado um trigger que irá esperar 
# que um reviewer em especifico de ok para que automaticamente essa PR seja recriada e lançada para outra branch.

name: Automate pulll request workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Test'
        default: 'Write something...'
        required: true

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        id: cpr
        uses: grmelito/SwagLabs-Tests@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: false
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/grmelito/SwagLabs-Tests
          labels: |
            report
            automated pr
          assignees: GuilhermeGonzalez
          reviewers: GuilhermeGonzalez
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
